// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import * as apiTypes from './put-bid-request.type';

export const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/PutBidRequest",
    "definitions": {
        "PutBidRequest": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "priceDecimal": {
                    "$ref": "#/definitions/BigNumber"
                },
                "payouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Part"
                    }
                },
                "originFees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Part"
                    }
                }
            },
            "required": [
                "hash",
                "priceDecimal"
            ],
            "additionalProperties": false
        },
        "BigNumber": {
            "type": "string"
        },
        "Part": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/Address"
                },
                "value": {
                    "type": "number"
                }
            },
            "required": [
                "account",
                "value"
            ],
            "additionalProperties": false
        },
        "Address": {
            "type": "string"
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validatePutBidRequest(payload: unknown): apiTypes.PutBidRequest {
  if (!isPutBidRequest(payload)) {
    const error = new Error('invalid payload: PutBidRequest');
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isPutBidRequest(payload: unknown): payload is apiTypes.PutBidRequest {
  /** Schema is defined in {@link SCHEMA.definitions.PutBidRequest } **/
  const ajvValidate = ajv.compile({ "$ref": "SCHEMA#/definitions/PutBidRequest" });
  return ajvValidate(payload);
}
